(() => {
  'use strict';

  // ─── Inline icons (vanilla SVG, mirrors quay-dashboard-v2's I object) ──
  const s = (inner) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`;
  const I = {
    layers: s('<path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 13 9 5 9-5"/>'),
    alert:  s('<path d="M12 3 2 20h20L12 3Z"/><path d="M12 9v5M12 17h.01"/>'),
    target: s('<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.4"/>'),
    check:  s('<path d="M20 6 9 17l-5-5"/>'),
  };

  // ─── Helpers ─────────────────────────────────────────────────────────
  const escapeHtml = (str) => String(str ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  const fmt = (n) => {
    if (n == null || isNaN(n)) return '0';
    return Math.round(Number(n)).toLocaleString('en-GB');
  };

  // ─── HubSpot Out-of-Date Deals view ──────────────────────────────────
  // The 3 Dialfire-overlay columns (Avg Logged / Avg Answered / Avg NA)
  // are intentionally not in this list yet - they would render as 14 columns
  // of em-dashes until the Dialfire overlay lands. They'll come back as
  // additional entries once that data is wired in.
  const HUBSPOT_COLS = [
    { k: 'calling',    label: 'Calling',      tip: 'Calling leads - outdated / total',     isStage: true },
    { k: 'external',   label: 'External',     tip: 'External leads - outdated / total',    isStage: true },
    { k: 'inbound',    label: 'Inbound',      tip: 'Inbound leads - outdated / total',     isStage: true },
    { k: 'reconv',     label: 'Reconv',       tip: 'Reconverted leads - outdated / total', isStage: true },
    { k: 'rental',     label: 'Rental',       tip: 'Rental leads - outdated / total',      isStage: true },
    { k: 'nurture',    label: 'Nurture',      tip: 'Leads to nurture - outdated / total',  isStage: true },
    { k: 'warm',       label: 'Warm',         tip: 'Warm leads - outdated / total',        isStage: true },
    { k: 'hot',        label: 'Hot',          tip: 'Hot leads - outdated / total',         isStage: true },
    { k: 'outdated',   label: 'Outdated',     tip: 'Total outdated leads across all stages' },
    { k: 'upToHot',    label: 'Up to Hot',    tip: 'Total deals in stages up to Hot Lead' },
    { k: 'pctUpdated', label: '% Updated',    tip: 'Share of leads with a future next-activity date', isPct: true },
  ];

  // Filter chips above the table - restrict the visible roster to a
  // worth-acting-on subset. Director-mode triage.
  const HUBSPOT_FILTERS = [
    { k: 'all',       label: 'All teams',     test: () => true },
    { k: 'stale50',   label: 'Stale > 50%',   test: (r) => r._stalePct >= 0.5 && r._tot > 0 },
    { k: 'stale80',   label: 'Stale > 80%',   test: (r) => r._stalePct >= 0.8 && r._tot > 0 },
    { k: 'hot',       label: 'Hot leads only',test: (r) => (r.total && r.total.hot || 0) > 0 },
    { k: 'hotStale',  label: 'Hot + stale',   test: (r) => (r.outdated && r.outdated.hot || 0) > 0 },
  ];

  let _hubspot = null;
  let _hubspotLoading = false;
  let _hubspotGroup = '1';
  let _hubspotSortBy = 'pctUpdated';
  let _hubspotSortDir = 'asc';   // worst first
  let _hubspotShowEmpty = false; // hide rows with 0 deals
  let _hubspotFilter = 'all';

  // ─── Divisions / Directory state ──────────────────────────────────────
  // Sourced from data/divisions.json (generated by scripts/parse_divisions.py
  // from the Divisions Area Breakdown.xlsx). Used to drill-down on a team
  // row (brokers + specialists + suburbs) and to power the Directory tab.
  let _divisions = null;
  let _divisionsLoading = false;
  let _tab = 'deals';                          // 'deals' | 'directory' | 'recruitment'
  let _dirSearch = '';
  let _dirSection = 'all';                     // section filter on Directory
  let _drillTeam = null;                       // team name when modal open
  let _recruitForm = 'contract';               // 'contract' | 'progress'; active recruitment sub-view
  // Signed-in user (set by enterApp once auth.js confirms the session):
  // { username, name, email, isSuper, isAdmin, isBroker, role }. Used to gate
  // the UI (broker vs super/admin); the backend derives identity from the JWT.
  let _currentUser = null;
  // Progress-report state (Recruitment → Progress sub-view).
  let _progress = null;          // { ok, candidates:[...] } once loaded
  let _progressLoading = false;
  let _progressError = null;
  let _progressExpanded = null;  // folderId of the row whose programs editor is open
  // Recruitment backend (Google Apps Script Web App). Every authenticated call
  // sends the caller's fresh Supabase JWT (AUTH.getAccessToken()) in the POST
  // body; the backend verifies identity and ownership. There is deliberately no
  // shared secret in the client: a public token in every broker's browser could
  // be replayed to bypass per-broker ownership checks.
  const RECRUIT_ENDPOINT = 'https://script.google.com/macros/s/AKfycbzBdDmvtpoQgIEdtopdh8iFK6vuD9Xvmt4OJUDdQEg9qeKgaOP3a_WOeVM4WaQU6PpZ/exec';

  async function loadHubspot() {
    if (_hubspotLoading) return;
    _hubspotLoading = true;
    try {
      const r = await fetch('data/hubspot_outdated.json?cb=' + Date.now());
      if (!r.ok) throw new Error('HTTP ' + r.status);
      _hubspot = await r.json();
    } catch (e) {
      console.warn('[hubspot] load failed', e);
      _hubspot = { error: String(e.message || e), generated: null, groups: { '1': [], '2': [], '3': [] } };
    } finally {
      _hubspotLoading = false;
      render();
    }
  }

  async function loadDivisions() {
    if (_divisionsLoading) return;
    _divisionsLoading = true;
    try {
      const r = await fetch('data/divisions.json?cb=' + Date.now());
      if (!r.ok) throw new Error('HTTP ' + r.status);
      _divisions = await r.json();
    } catch (e) {
      console.warn('[divisions] load failed', e);
      _divisions = { error: String(e.message || e), generated: null, sections: [] };
    } finally {
      _divisionsLoading = false;
      render();
    }
  }

  // Build a normalized lookup: lowercased team name → { team, section }.
  // Some sheet rows have trailing whitespace ("Wizards "), so we trim.
  let _teamLookupCache = null;
  function _teamLookup() {
    if (_teamLookupCache) return _teamLookupCache;
    const m = new Map();
    if (_divisions && _divisions.sections) {
      _divisions.sections.forEach(sec => {
        sec.teams.forEach(t => {
          const key = (t.name || '').toLowerCase().trim();
          if (key) m.set(key, { team: t, section: sec.name });
        });
      });
    }
    _teamLookupCache = m;
    return m;
  }
  function divisionForTeam(name) {
    const k = (name || '').toLowerCase().trim();
    return _teamLookup().get(k) || null;
  }

  function render() {
    const host = document.getElementById('content');
    if (_tab === 'recruitment') {
      // Team dropdown is built from the division directory - load it if needed.
      if (_divisions == null && !_divisionsLoading) loadDivisions();
      host.innerHTML = renderRecruitment();
      wireRecruitment();
    } else if (_tab === 'directory') {
      if (_divisions == null && !_divisionsLoading) loadDivisions();
      host.innerHTML = renderDirectory();
      wireDirectory();
    } else {
      // Deals tab - load divisions in the background so the drill-down
      // is ready when a team row is clicked.
      if (_divisions == null && !_divisionsLoading) loadDivisions();
      host.innerHTML = renderHubspot();
      wireHubspot();
    }
    // Tab nav active state.
    document.querySelectorAll('#tabNav .tab-btn').forEach(b => {
      b.classList.toggle('active', b.dataset.tab === _tab);
    });
    // Render the drill-down modal if open.
    const modalHost = document.getElementById('modalHost');
    if (modalHost) {
      modalHost.innerHTML = _drillTeam ? renderTeamDrillDown() : '';
      if (_drillTeam) wireTeamDrillDown();
    }
    // Mirror the refresh badge into the sticky topbar so the freshness
    // signal stays visible when the user has scrolled past the title card.
    const topbarSlot = document.getElementById('topbarRefresh');
    if (topbarSlot && _hubspot && _hubspot.generated) {
      const d = new Date(_hubspot.generated);
      const hrs = (Date.now() - d.getTime()) / 3600000;
      // Threshold tuned to the 3× daily cadence (03:00 / 11:00 / 13:00
      // SAST). Anything older than ~9h between expected refreshes is
      // warn-worthy; anything past a full day is bad.
      const cls = hrs < 9 ? 'ok' : hrs < 24 ? 'warn' : 'bad';
      const mins = Math.max(0, Math.round((Date.now() - d.getTime()) / 60000));
      const rel = mins < 60 ? mins + 'm ago'
                : hrs  < 24 ? Math.round(hrs) + 'h ago'
                : Math.round(hrs / 24) + 'd ago';
      const abs = d.toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Africa/Johannesburg' }) + ' SAST';
      const nextRun = _nextRefreshSAST();
      const tip = `Last refresh: ${abs}${nextRun ? `\nNext scheduled: ${nextRun} SAST` : ''}`;
      topbarSlot.innerHTML = `<span class="pill ${cls}" title="${escapeHtml(tip)}">Refreshed ${escapeHtml(rel)}</span>`;
    } else if (topbarSlot) {
      topbarSlot.innerHTML = '';
    }
  }

  // The fetch-hubspot workflow runs at 03:00 / 11:00 / 13:00 SAST. Pick
  // the next one ahead of now in local-SAST terms - used in the refresh
  // pill tooltip so the operator sees when fresh data is due.
  function _nextRefreshSAST() {
    const SCHEDULE_H = [3, 11, 13];
    // SAST is UTC+2, no DST. Compute "now" in SAST by adding 2h to UTC.
    const utc = new Date();
    const sast = new Date(utc.getTime() + 2 * 3600 * 1000);
    const hourNow = sast.getUTCHours();
    const minNow  = sast.getUTCMinutes();
    const todayRunsAhead = SCHEDULE_H.filter(h => h > hourNow || (h === hourNow && minNow === 0));
    if (todayRunsAhead.length) {
      const h = todayRunsAhead[0];
      return String(h).padStart(2, '0') + ':00 today';
    }
    return String(SCHEDULE_H[0]).padStart(2, '0') + ':00 tomorrow';
  }

  // ─── Helpers shared across the render ──────────────────────────────
  const _num = (v) => { const n = Number(v); return isFinite(n) ? n : 0; };
  const _stalePctOf = (r) => {
    const t = _num(r.total && r.total.deals);
    const o = _num(r.outdated && r.outdated.outdated);
    return t > 0 ? o / t : 0;
  };
  // Compact integer formatter for tight cells ("29.4k" instead of "29431").
  const _fmtK = (n) => {
    const v = Math.abs(Number(n) || 0);
    if (v >= 100000) return (v / 1000).toFixed(0) + 'k';
    if (v >= 10000)  return (v / 1000).toFixed(1) + 'k';
    return String(Math.round(Number(n) || 0));
  };

  function _hsKpiForGroup(rows) {
    const total = rows.reduce((s, r) => s + _num(r.total && r.total.deals), 0);
    const out   = rows.reduce((s, r) => s + _num(r.outdated && r.outdated.outdated), 0);
    const pctRows = rows.filter(r => r.outdated && r.outdated.pctUpdated != null);
    const avg = pctRows.length
      ? pctRows.reduce((s, r) => s + _num(r.outdated.pctUpdated), 0) / pctRows.length
      : 0;
    return { totalDeals: total, outdatedLeads: out,
             pctOutdated: total > 0 ? out / total : 0,
             avgPctUpdated: avg, reportingTeams: pctRows.length };
  }

  function renderHubspot() {
    if (_hubspot == null && !_hubspotLoading) loadHubspot();
    if (_hubspot == null) {
      return `<div class="tab-view"><div class="card card-pad" style="text-align:center;color:var(--muted);padding:60px 20px">Loading HubSpot figures…</div></div>`;
    }

    const groups     = (_hubspot.groups) || { '1': [], '2': [], '3': [] };
    const groupNames = (_hubspot.groupNames) || { '1': 'Group 1', '2': 'Group 2', '3': 'Group 3' };
    const allRows    = groups[_hubspotGroup] || [];
    const portalId   = _hubspot.portalId || null;

    // Decorate rows with cached _tot / _stalePct used by the filter, the
    // top-3 callout, and the sort comparator.
    allRows.forEach(r => {
      r._tot = _num(r.total && r.total.deals);
      r._out = _num(r.outdated && r.outdated.outdated);
      r._stalePct = r._tot > 0 ? r._out / r._tot : 0;
    });

    // Apply filter, then "hide empty teams" toggle, then sort.
    const filter = HUBSPOT_FILTERS.find(f => f.k === _hubspotFilter) || HUBSPOT_FILTERS[0];
    let visible = allRows.filter(filter.test);
    if (!_hubspotShowEmpty) visible = visible.filter(r => r._tot > 0);

    // Sort comparator. Default 'pctUpdated' asc puts the worst-performing
    // teams (with deals) at the top - that's the triage view a director
    // opens the dashboard for.
    visible = visible.slice().sort((a, b) => {
      const k = _hubspotSortBy;
      const av = (k === 'team'    ? (a.team || '').toLowerCase()
               : k === 'total'   ? a._tot
               : k === 'outdated' ? a._out
               : k === 'pctUpdated' ? (a.outdated && a.outdated.pctUpdated != null ? a.outdated.pctUpdated : 2)  // empty rows last
               : _num(a.outdated && a.outdated[k]));
      const bv = (k === 'team'    ? (b.team || '').toLowerCase()
               : k === 'total'   ? b._tot
               : k === 'outdated' ? b._out
               : k === 'pctUpdated' ? (b.outdated && b.outdated.pctUpdated != null ? b.outdated.pctUpdated : 2)
               : _num(b.outdated && b.outdated[k]));
      if (av < bv) return _hubspotSortDir === 'asc' ? -1 : 1;
      if (av > bv) return _hubspotSortDir === 'asc' ?  1 : -1;
      return 0;
    });

    const emptyCount  = allRows.filter(r => r._tot === 0).length;
    const hiddenByFil = allRows.length - visible.length - (_hubspotShowEmpty ? 0 : emptyCount);

    // ── Refresh badge ───────────────────────────────────────────────
    const genDate = _hubspot.generated ? new Date(_hubspot.generated) : null;
    const genAbs  = genDate
      ? genDate.toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'Africa/Johannesburg' }) + ' SAST'
      : null;
    const relAge = (d) => {
      if (!d) return null;
      const mins = Math.max(0, Math.round((Date.now() - d.getTime()) / 60000));
      if (mins < 60) return mins + 'm ago';
      const hrs = Math.round(mins / 60);
      if (hrs  < 24) return hrs  + 'h ago';
      return Math.round(hrs / 24) + 'd ago';
    };
    const ageClass = (() => {
      if (!genDate) return 'bad';
      const hrs = (Date.now() - genDate.getTime()) / 3600000;
      if (hrs < 30) return 'ok';
      if (hrs < 72) return 'warn';
      return 'bad';
    })();
    const refreshBadge = genDate
      ? `<span class="pill ${ageClass}" title="${escapeHtml(genAbs)}">Refreshed ${escapeHtml(relAge(genDate))}</span>`
      : `<span class="pill bad" title="Workflow has never populated data/hubspot_outdated.json">Snapshot - never refreshed</span>`;

    // ── KPIs + delta vs previous run ────────────────────────────────
    const kpi      = _hsKpiForGroup(allRows);
    const prevKpi  = (_hubspot._prev && _hubspot._prev.kpi && _hubspot._prev.kpi[_hubspotGroup]) || null;
    const deltaFmt = (cur, prev, unit, invertColour) => {
      if (prev == null || cur == null) return '';
      const d = cur - prev;
      if (Math.abs(d) < 0.0005) return '';
      const arrow = d > 0 ? '▲' : '▼';
      // For "% Outdated" and "Outdated Leads", UP is bad. For "% Updated"
      // and "Total Deals", UP is good. invertColour=true flips the
      // green/red mapping for the bad-is-up metrics.
      const up = d > 0;
      const good = invertColour ? !up : up;
      const cls = good ? 'kpi-delta kpi-delta--up' : 'kpi-delta kpi-delta--down';
      const txt = unit === '%' ? `${Math.abs(d * 100).toFixed(1)} pts` : fmt(Math.round(Math.abs(d)));
      return `<span class="${cls}" title="vs previous refresh">${arrow} ${txt}</span>`;
    };
    const kpiCard = (icon, label, val, foot, delta, heroClass) => `<div class="card kpi ${heroClass || ''}">
      <div class="kpi-top"><div class="kpi-ic">${icon}</div></div>
      <div class="kpi-label">${escapeHtml(label)}</div>
      <div class="kpi-valrow"><span class="kpi-val tnum">${val}</span>${delta || ''}</div>
      <div class="kpi-foot">${escapeHtml(foot)}</div>
    </div>`;

    // Hero KPI tint by current % outdated value.
    const heroClass = (() => {
      const p = kpi.pctOutdated * 100;
      if (p >= 60) return 'kpi--hero-bad';
      if (p >= 30) return 'kpi--hero-warn';
      return 'kpi--hero-ok';
    })();

    // ── Group seg control: now includes health % per group ──────────
    const segBtn = (k) => {
      const gRows = groups[k] || [];
      const gk    = _hsKpiForGroup(gRows);
      const stale = gk.totalDeals > 0 ? (gk.outdatedLeads / gk.totalDeals) * 100 : 0;
      const staleClass = stale >= 60 ? 'seg-stale-bad' : stale >= 30 ? 'seg-stale-warn' : 'seg-stale-ok';
      const name  = groupNames[k] || ('Group ' + k);
      // Drop the team count from the button - it's already in the table
      // header below. Keep just `name · X% stale` so the segment header
      // does one thing: signal which group is hottest.
      return `<button class="${k === _hubspotGroup ? 'active' : ''}" data-hs-group="${k}" aria-pressed="${k === _hubspotGroup ? 'true' : 'false'}">
        ${escapeHtml(name)}
        ${gk.totalDeals > 0 ? `<span class="seg-meta ${staleClass}">· ${stale.toFixed(0)}% stale</span>` : ''}
      </button>`;
    };

    // ── Top-3 needs-attention callout ───────────────────────────────
    // Score = absolute outdated count × outdated share. Rewards teams
    // that are both large and bad - the director's emails-to-send list.
    const top3 = allRows
      .filter(r => r._tot >= 5 && r._stalePct >= 0.3)
      .map(r => ({ row: r, score: r._out * r._stalePct }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);
    const hubspotLinkFor = (r) => {
      if (!portalId || !r.ownerIds || !r.ownerIds.length) return null;
      // Filter the HubSpot deal-list to this team's owners. Field name
      // 'hubspot_owner_id' is HubSpot's standard owner filter param.
      return `https://app.hubspot.com/contacts/${encodeURIComponent(portalId)}/objects/0-3/views/all/list` +
             `?query=&filters=%5B%7B%22property%22%3A%22hubspot_owner_id%22%2C%22operator%22%3A%22IN%22%2C%22values%22%3A%5B${r.ownerIds.map(encodeURIComponent).join('%2C')}%5D%7D%5D`;
    };
    const top3Html = top3.length === 0
      ? `<div class="muted" style="font-size:13px">No teams flagged for attention in ${escapeHtml(groupNames[_hubspotGroup])} - every team with ≥5 deals is below the 30% stale threshold.</div>`
      : top3.map(({ row: r }, i) => {
          const link = hubspotLinkFor(r);
          const stalePct = (r._stalePct * 100).toFixed(0);
          const inner = `
            <div class="t3-rank">${i + 1}</div>
            <div class="t3-body">
              <div class="t3-name">${escapeHtml(r.team)}</div>
              <div class="t3-stats">
                <span class="t3-stat"><b>${fmt(r._out)}</b> stale of <b>${fmt(r._tot)}</b></span>
                <span class="t3-stat t3-pct" style="color:${r._stalePct >= 0.6 ? 'var(--red)' : r._stalePct >= 0.3 ? 'var(--amber)' : 'var(--green)'}">${stalePct}% stale</span>
              </div>
            </div>
            ${link ? `<div class="t3-go" aria-hidden="true">→</div>` : ''}`;
          return link
            ? `<a class="t3-card" href="${link}" target="_blank" rel="noopener" title="Open this team's deals in HubSpot">${inner}</a>`
            : `<div class="t3-card t3-card--static">${inner}</div>`;
        }).join('');

    // ── Filter chips ────────────────────────────────────────────────
    const filterChips = HUBSPOT_FILTERS.map(f => {
      const count = allRows.filter(r => r._tot > 0).filter(f.test).length;
      // Always show the count - even 0 - so the user sees the filter is
      // empty BEFORE clicking it. Mute zero counts so they recede.
      const zero = count === 0 ? ' chip-count--zero' : '';
      return `<button class="chip ${f.k === _hubspotFilter ? 'active' : ''}" data-hs-filter="${f.k}" aria-pressed="${f.k === _hubspotFilter ? 'true' : 'false'}">
        ${escapeHtml(f.label)}<span class="chip-count${zero}">${count}</span>
      </button>`;
    }).join('');

    // ── Cell formatters + colour ───────────────────────────────────
    const fmtCell = (v, isPct) => {
      if (v == null || v === '') return '<span class="empty">-</span>';
      if (isPct) return (Number(v) * 100).toFixed(1) + '%';
      const n = Number(v);
      return isFinite(n) ? n.toFixed(n % 1 === 0 ? 0 : 1) : escapeHtml(String(v));
    };
    // Stage cell: "outdated/total" with green/red colour + accessibility
    // marker so the meaning isn't carried only by hue. ✓ when none stale,
    // ⚠ when all stale.
    const stageCell = (outdatedN, totalN) => {
      if (!totalN) return '<td class="num"><span class="empty">-</span></td>';
      const out = Number(outdatedN || 0);
      const tot = Number(totalN);
      const allStale  = tot > 0 && out === tot;
      const noneStale = out === 0;
      const colour = allStale  ? 'color:var(--red);font-weight:700'
                   : noneStale ? 'color:var(--green);font-weight:700'
                               : 'color:var(--ink);font-weight:600';
      // Only flag the worst case (all stale). Per-cell ✓ ticks across 8
      // stage columns were pure noise; the green numerator already reads
      // as "none stale". Summary pills keep their ✓/⚠ (real signal).
      const marker = allStale ? ' ⚠' : '';
      // Colour applies to the numerator (outdated); denominator recedes.
      const display = `${_fmtK(out)}<span class="cell-slash">/</span><span class="cell-den">${_fmtK(tot)}</span>${marker}`;
      const title = `${out} outdated of ${tot} total`;
      return `<td class="num tnum" style="${colour}" title="${title}">${display}</td>`;
    };
    const pctClass = (frac) => {
      if (frac == null) return '';
      const p = Number(frac) * 100;
      if (p >= 85) return 'ok';
      if (p >= 70) return 'warn';
      return 'bad';
    };
    const outdatedClass = (outdatedN, totalN) => {
      if (!totalN || totalN <= 0 || outdatedN == null) return '';
      const share = outdatedN / totalN;
      if (share >= 0.30) return 'bad';
      if (share >= 0.15) return 'warn';
      return 'ok';
    };
    const pctCell = (frac) => {
      if (frac == null) return '<td class="num"><span class="empty">-</span></td>';
      const cls = pctClass(frac);
      const sym = cls === 'ok' ? ' ✓' : cls === 'bad' ? ' ⚠' : '';
      return `<td class="num"><span class="pill ${cls}">${(Number(frac) * 100).toFixed(1)}%${sym}</span></td>`;
    };
    const outdatedCell = (outdatedN, totalN) => {
      if (outdatedN == null) return '<td class="num"><span class="empty">-</span></td>';
      const cls = outdatedClass(Number(outdatedN), Number(totalN));
      if (!cls) return `<td class="num tnum">${fmt(Math.round(outdatedN))}</td>`;
      const sym = cls === 'bad' ? ' ⚠' : cls === 'ok' ? ' ✓' : '';
      return `<td class="num"><span class="pill ${cls}" style="font-variant-numeric:tabular-nums">${fmt(Math.round(outdatedN))}${sym}</span></td>`;
    };
    const sumCol = (k) => visible.reduce((s, r) => s + _num(r.outdated && r.outdated[k]), 0);

    const STK_TH  = 'position:sticky;left:0;z-index:2;background:var(--paper-2);box-shadow:1px 0 0 var(--line-2)';
    const STK_TD  = 'position:sticky;left:0;z-index:1;background:var(--card);box-shadow:1px 0 0 var(--line-2);white-space:nowrap';
    const STK_TOT = 'position:sticky;left:0;z-index:1;background:#F7F8FC;box-shadow:1px 0 0 var(--line-2)';
    // Pin the HubSpot-link column to the RIGHT edge too, so the one action
    // button is always reachable and never scrolls off (the clipping bug).
    const STK_TH_R  = 'position:sticky;right:0;z-index:2;background:var(--paper-2);box-shadow:-1px 0 0 var(--line-2)';
    const STK_TD_R  = 'position:sticky;right:0;z-index:1;background:var(--card);box-shadow:-1px 0 0 var(--line-2)';
    const STK_TOT_R = 'position:sticky;right:0;z-index:1;background:#F7F8FC;box-shadow:-1px 0 0 var(--line-2)';

    // Sort indicator on the active column header.
    const sortIndic = (k) => {
      if (k !== _hubspotSortBy) return '<span class="sort-ind" aria-hidden="true"> ⇅</span>';
      return _hubspotSortDir === 'asc'
        ? '<span class="sort-ind sort-ind--active" aria-hidden="true"> ▲</span>'
        : '<span class="sort-ind sort-ind--active" aria-hidden="true"> ▼</span>';
    };
    // aria-sort lets assistive tech announce sort state without relying
    // on the glyph alone (WCAG 1.3.1).
    const ariaSort = (k) => k === _hubspotSortBy
      ? (_hubspotSortDir === 'asc' ? 'ascending' : 'descending')
      : 'none';

    const headerCellForStage = (c) =>
      `<th class="num" style="min-width:${c.k === 'pctUpdated' ? 96 : 78}px" title="${escapeHtml(c.tip)}" data-hs-sort="${c.k}" aria-sort="${ariaSort(c.k)}" scope="col">${escapeHtml(c.label)}${sortIndic(c.k)}</th>`;
    const headerNumeric = (k, label, tip, w) =>
      `<th class="num" style="min-width:${w}px" title="${escapeHtml(tip)}" data-hs-sort="${k}" aria-sort="${ariaSort(k)}" scope="col">${escapeHtml(label)}${sortIndic(k)}</th>`;
    const teamHeader = `<th style="${STK_TH};min-width:180px;text-align:left" data-hs-sort="team" aria-sort="${ariaSort('team')}" scope="col">Team${sortIndic('team')}</th>`;
    const totalHeader = headerNumeric('total', 'Total', 'Total deals for this team', 74);

    const emptyRow = `<tr><td colspan="${HUBSPOT_COLS.length + 2}" class="muted" style="text-align:center;padding:36px 20px;line-height:1.55">
      No data loaded yet - the dashboard refresh hasn't run.<br>
      Trigger it from the repo's <b>Actions → Fetch HubSpot Deals</b> tab,
      or wait for the next scheduled run (03:00 / 11:00 / 13:00 SAST).
    </td></tr>`;
    const noVisibleRow = `<tr><td colspan="${HUBSPOT_COLS.length + 2}" class="muted" style="text-align:center;padding:36px 20px;line-height:1.55">
      No teams match the current filter / hidden-empties setting.
    </td></tr>`;

    return `<div class="tab-view">

      <div class="card card-pad hs-titlebar">
        <div style="display:flex;flex-wrap:wrap;gap:14px;align-items:flex-start;justify-content:space-between">
          <div style="min-width:0;flex:1 1 320px">
            <div style="display:flex;flex-wrap:wrap;align-items:center;gap:10px">
              <h3 style="margin:0;font-family:var(--serif);font-size:17px;color:var(--ink)">Out-of-Date Deals · per team</h3>
              ${refreshBadge}
            </div>
            <div class="sub" style="margin-top:6px">
              Mirrors the RAW DATA DEALS spreadsheet · pulled from HubSpot
              ${genAbs ? ` · ${escapeHtml(genAbs)}` : ''}
            </div>
          </div>
          <div class="seg seg-with-meta" id="hsGroupSeg" style="flex-wrap:wrap">
            ${segBtn('1')}${segBtn('2')}${segBtn('3')}
          </div>
        </div>
        ${_hubspot.error ? `<div class="banner" style="margin-top:12px;background:var(--red-tint);color:var(--red);padding:8px 10px;border-radius:6px;font-size:12.5px">Data not loaded - ${escapeHtml(_hubspot.error)}. The GH Action will populate it on its next run.</div>` : ''}
      </div>

      <div class="row kpis mt">
        ${kpiCard(I.alert,  'Outdated Leads',
                  fmt(kpi.outdatedLeads),
                  'sum of stale leads across the group',
                  deltaFmt(kpi.outdatedLeads, prevKpi && prevKpi.outdatedLeads, '', true))}
        ${kpiCard(I.target, '% Outdated',
                  (kpi.pctOutdated * 100).toFixed(1) + '%',
                  'outdated ÷ total deals',
                  deltaFmt(kpi.pctOutdated, prevKpi && prevKpi.pctOutdated, '%', true),
                  heroClass)}
        ${kpiCard(I.check,  'Avg % Updated',
                  (kpi.avgPctUpdated * 100).toFixed(1) + '%',
                  'mean across ' + kpi.reportingTeams + ' reporting team' + (kpi.reportingTeams === 1 ? '' : 's'),
                  deltaFmt(kpi.avgPctUpdated, prevKpi && prevKpi.avgPctUpdated, '%', false))}
        ${kpiCard(I.layers, 'Total Deals',
                  fmt(kpi.totalDeals),
                  escapeHtml(groupNames[_hubspotGroup] || ('Group ' + _hubspotGroup)) + ' · ' + allRows.length + ' team' + (allRows.length === 1 ? '' : 's'),
                  deltaFmt(kpi.totalDeals, prevKpi && prevKpi.totalDeals, '', false))}
      </div>

      <div class="card mt card-pad">
        <div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:10px">
          <div style="font-family:var(--serif);font-size:14px;font-weight:700;color:var(--ink);text-transform:uppercase;letter-spacing:.04em">Needs attention</div>
          <div class="sub">Top 3 worst stale ratios in ${escapeHtml(groupNames[_hubspotGroup])} (≥ 5 deals, ≥ 30% stale)</div>
        </div>
        <div class="t3-grid">${top3Html}</div>
      </div>

      <div class="card mt card-pad" style="display:flex;flex-wrap:wrap;gap:10px;align-items:center;justify-content:space-between">
        <div class="chips">${filterChips}</div>
        <label style="display:inline-flex;gap:6px;align-items:center;font-size:12.5px;color:var(--slate);cursor:pointer">
          <input id="hsShowEmpty" type="checkbox" ${_hubspotShowEmpty ? 'checked' : ''}>
          Show ${emptyCount} team${emptyCount === 1 ? '' : 's'} with no deals
        </label>
      </div>

      <div class="card mt">
        <div class="tbl-wrap"><table class="tbl tbl-sortable">
          <thead><tr>
            ${teamHeader}
            ${totalHeader}
            ${HUBSPOT_COLS.map(c => headerCellForStage(c)).join('')}
            ${portalId ? `<th class="num" style="${STK_TH_R};min-width:96px;text-align:right" title="Open this team's deals in HubSpot" scope="col">HubSpot</th>` : ''}
          </tr></thead>
          <tbody>
            ${allRows.length === 0 ? emptyRow : (visible.length === 0 ? noVisibleRow : visible.map(r => {
              const tot      = r._tot;
              const outdated = r.outdated ? r.outdated.outdated : null;
              const dim = r._tot === 0 ? ' style="opacity:.55"' : '';
              const link = hubspotLinkFor(r);
              const divInfo = divisionForTeam(r.team);
              const teamClickable = !!divInfo;
              return `<tr${dim}${teamClickable ? ` class="row-team" data-team-name="${escapeHtml(r.team)}" tabindex="0" role="button" aria-label="Open ${escapeHtml(r.team)} division details"` : ''}>
                <td style="${STK_TD}"><div class="agent-cell"><div class="agent-name">${escapeHtml(r.team || '-')}${teamClickable ? '<span class="team-chev" aria-hidden="true">›</span>' : ''}</div>${r._tot === 0 ? '<span class="pill" style="background:var(--paper);color:var(--muted);font-size:10px;margin-left:6px">No deals</span>' : ''}</div></td>
                <td class="num tnum">${fmt(tot)}</td>
                ${HUBSPOT_COLS.map(c => {
                  if (c.k === 'pctUpdated') return pctCell(r.outdated ? r.outdated[c.k] : null);
                  if (c.k === 'outdated')   return outdatedCell(outdated, tot);
                  if (c.isStage) {
                    const o = r.outdated ? r.outdated[c.k] : null;
                    const t = r.total    ? r.total[c.k]    : null;
                    return stageCell(o, t);
                  }
                  return `<td class="num tnum">${fmtCell(r.outdated ? r.outdated[c.k] : null, c.isPct)}</td>`;
                }).join('')}
                ${portalId ? `<td class="num" style="${STK_TD_R}">${link ? `<a class="row-go" href="${link}" target="_blank" rel="noopener" title="Open in HubSpot" aria-label="Open ${escapeHtml(r.team || '')} deals in HubSpot"><span class="row-go-text">HubSpot</span><span class="row-go-arrow" aria-hidden="true">↗</span></a>` : '<span class="empty">-</span>'}</td>` : ''}
              </tr>`;
            }).join(''))}
            ${visible.length > 0 ? `<tr class="tbl-total" style="background:#F7F8FC;font-weight:700">
              <td style="${STK_TOT}">Total · ${visible.length} team${visible.length === 1 ? '' : 's'}</td>
              <td class="num tnum">${fmt(visible.reduce((s, r) => s + r._tot, 0))}</td>
              ${HUBSPOT_COLS.map(c => {
                if (c.isPct) return `<td class="num"><span class="empty">-</span></td>`;
                if (c.isStage) {
                  const oSum = visible.reduce((s, r) => s + _num(r.outdated && r.outdated[c.k]), 0);
                  const tSum = visible.reduce((s, r) => s + _num(r.total && r.total[c.k]), 0);
                  return `<td class="num tnum">${_fmtK(oSum)}<span class="cell-slash">/</span><span class="cell-den">${_fmtK(tSum)}</span></td>`;
                }
                return `<td class="num tnum">${fmt(sumCol(c.k))}</td>`;
              }).join('')}
              ${portalId ? `<td style="${STK_TOT_R}"></td>` : ''}
            </tr>` : ''}
          </tbody>
        </table></div>
        ${hiddenByFil > 0 && _hubspotFilter !== 'all' ? `<div class="muted" style="font-size:12.5px;padding:10px 16px 14px">${hiddenByFil} additional team${hiddenByFil === 1 ? '' : 's'} hidden by the current filter.</div>` : ''}
      </div>
    </div>`;
  }

  // ─── Directory tab ────────────────────────────────────────────────────
  // Search-by-team / by-broker / by-suburb across the divisions JSON.
  // Section filter narrows to one division category (e.g. Rentals).
  function renderDirectory() {
    if (_divisions == null && !_divisionsLoading) loadDivisions();
    if (_divisions == null) {
      return `<div class="tab-view"><div class="card card-pad" style="text-align:center;color:var(--muted);padding:60px 20px">Loading division directory…</div></div>`;
    }
    if (_divisions.error) {
      return `<div class="tab-view"><div class="card card-pad" style="color:var(--red);text-align:center;padding:40px">
        Couldn't load <code>data/divisions.json</code> - ${escapeHtml(_divisions.error)}.<br>
        Run <code>python3 scripts/parse_divisions.py</code> to regenerate it.</div></div>`;
    }

    const sections = _divisions.sections || [];
    const q = (_dirSearch || '').toLowerCase().trim();

    // Score-and-filter teams. A team matches if its name, any broker /
    // specialist name, or its suburbs contain the query. Section filter
    // narrows further.
    const matchTeam = (t) => {
      if (!q) return true;
      if ((t.name || '').toLowerCase().includes(q)) return true;
      if ((t.suburbs || '').toLowerCase().includes(q)) return true;
      const allContacts = (t.brokers || []).concat(t.specialists || []);
      return allContacts.some(c =>
        (c.name  || '').toLowerCase().includes(q) ||
        (c.email || '').toLowerCase().includes(q));
    };

    const filteredSections = sections
      .filter(s => _dirSection === 'all' || s.name === _dirSection)
      .map(s => ({ ...s, teams: (s.teams || []).filter(matchTeam) }))
      .filter(s => s.teams.length > 0);

    const totalTeams = filteredSections.reduce((n, s) => n + s.teams.length, 0);
    const totalAll   = sections.reduce((n, s) => n + (s.teams || []).length, 0);

    const sectionOpts = ['<option value="all">All categories</option>']
      .concat(sections.map(s =>
        `<option value="${escapeHtml(s.name)}" ${_dirSection === s.name ? 'selected' : ''}>${escapeHtml(s.name)}</option>`
      )).join('');

    const renderTeamCard = (t) => {
      const brokers = (t.brokers || []).filter(b => b.name);
      const specs   = (t.specialists || []).filter(s => s.name && !/^Quay 1 Property Specialist/i.test(s.name));
      const hasHubspot = !!t.hubspot_owner_id;
      const brokerChip = (c) => {
        // Guard against dirty source data: only treat a value as a phone when
        // it actually reads like one (has digits, no '@', not a copy of the
        // email). Prevents a broken tel:name@domain link when a row's phone
        // cell was populated with the email by mistake.
        const rawPhone = String(c.phone || '').trim();
        const isPhone = rawPhone && !rawPhone.includes('@') && /\d/.test(rawPhone) &&
                        rawPhone.toLowerCase() !== String(c.email || '').trim().toLowerCase();
        const tel = isPhone ? `<a href="tel:${escapeHtml(rawPhone.replace(/\s/g, ''))}" class="dir-link" title="Call ${escapeHtml(c.name)}">${escapeHtml(rawPhone)}</a>` : '';
        const mail = c.email ? `<a href="mailto:${escapeHtml(c.email)}" class="dir-link" title="Email ${escapeHtml(c.name)}">${escapeHtml(c.email)}</a>` : '';
        return `<div class="dir-contact">
          <div class="dir-contact-name">${escapeHtml(c.name)}</div>
          <div class="dir-contact-meta">${mail}${mail && tel ? ' · ' : ''}${tel}</div>
        </div>`;
      };
      return `<button class="dir-card" data-team-name="${escapeHtml(t.name)}" aria-label="Open ${escapeHtml(t.name)} division details">
        <div class="dir-card-head">
          <div>
            <div class="dir-card-name">${escapeHtml(t.name)}</div>
            <div class="dir-card-meta">
              ${t.type ? `<span class="pill ${(/rental/i).test(t.type) ? 'pill-rental' : (/commercial/i).test(t.type) ? 'pill-commercial' : 'pill-sales'}">${escapeHtml(t.type.trim())}</span>` : ''}
              ${hasHubspot ? `<span class="dir-meta-item">Owner ID ${escapeHtml(t.hubspot_owner_id)}</span>` : ''}
              <span class="dir-meta-item">${brokers.length} broker${brokers.length === 1 ? '' : 's'}${specs.length ? ` · ${specs.length} specialist${specs.length === 1 ? '' : 's'}` : ''}</span>
            </div>
          </div>
          <div class="dir-card-chev" aria-hidden="true">›</div>
        </div>
        ${t.suburbs ? `<div class="dir-suburbs">${escapeHtml(t.suburbs)}</div>` : ''}
        ${brokers.length ? `<div class="dir-contacts">${brokers.slice(0, 2).map(brokerChip).join('')}${brokers.length > 2 ? `<div class="dir-more">+${brokers.length - 2} more</div>` : ''}</div>` : ''}
      </button>`;
    };

    const sectionBlocks = filteredSections.map(s => `
      <div class="dir-section">
        <div class="dir-section-head">
          <h3>${escapeHtml(s.name)}</h3>
          <span class="dir-section-count">${s.teams.length} team${s.teams.length === 1 ? '' : 's'}</span>
        </div>
        <div class="dir-grid">${s.teams.map(renderTeamCard).join('')}</div>
      </div>
    `).join('');

    return `<div class="tab-view">
      <div class="card card-pad dir-titlebar">
        <div style="display:flex;flex-wrap:wrap;gap:14px;align-items:flex-start;justify-content:space-between">
          <div style="min-width:0;flex:1 1 320px">
            <h3 style="margin:0;font-family:var(--serif);font-size:17px;color:var(--ink)">Divisions Directory</h3>
            <div class="sub" style="margin-top:6px">
              Brokers · specialists · suburbs · HubSpot owner IDs ·
              ${totalAll} teams across ${sections.length} division${sections.length === 1 ? '' : 's'}
            </div>
          </div>
        </div>
        <div class="dir-controls">
          <input id="dirSearch" type="search" placeholder="Search team, broker, or suburb…" value="${escapeHtml(_dirSearch || '')}" class="dir-search" autocomplete="off">
          <select id="dirSection" class="dir-section-select">${sectionOpts}</select>
        </div>
        ${q || _dirSection !== 'all'
          ? `<div class="dir-result-meta">${totalTeams} team${totalTeams === 1 ? '' : 's'} match${totalTeams === 1 ? 'es' : ''}${q ? ` "${escapeHtml(_dirSearch)}"` : ''}${_dirSection !== 'all' ? ` in ${escapeHtml(_dirSection)}` : ''}</div>`
          : ''}
      </div>
      ${totalTeams === 0
        ? `<div class="card card-pad" style="text-align:center;color:var(--muted);padding:48px 20px">No teams match the current search.</div>`
        : sectionBlocks}
    </div>`;
  }

  function wireDirectory() {
    const search = document.getElementById('dirSearch');
    if (search) {
      search.addEventListener('input', (e) => {
        _dirSearch = e.target.value;
        // Re-render only the result region for a snappier feel - but we
        // rebuild the whole tab to keep the result-meta line in sync.
        render();
        // Restore focus to the search (the re-render replaces the node).
        const s2 = document.getElementById('dirSearch');
        if (s2) { s2.focus(); s2.setSelectionRange(s2.value.length, s2.value.length); }
      });
    }
    const sel = document.getElementById('dirSection');
    if (sel) sel.addEventListener('change', (e) => { _dirSection = e.target.value; render(); });
    document.querySelectorAll('.dir-card[data-team-name]').forEach(b => {
      b.addEventListener('click', () => openTeamDrillDown(b.dataset.teamName));
    });
  }

  // ─── Team drill-down modal ────────────────────────────────────────────
  function openTeamDrillDown(teamName) {
    _drillTeam = teamName;
    render();
  }
  function closeTeamDrillDown() {
    _drillTeam = null;
    render();
  }
  function renderTeamDrillDown() {
    const info = divisionForTeam(_drillTeam);
    if (!info) {
      // Team isn't in the divisions sheet (e.g. retired team or naming
      // mismatch). Show a friendly empty-state so the click isn't silent.
      return `
        <div class="modal-back" data-modal-close></div>
        <div class="modal" role="dialog" aria-label="${escapeHtml(_drillTeam)} not found">
          <div class="modal-head">
            <h3>${escapeHtml(_drillTeam)}</h3>
            <button class="modal-close" data-modal-close aria-label="Close">✕</button>
          </div>
          <div class="modal-body">
            <div class="muted" style="text-align:center;padding:32px 8px">
              No division mapping found for <b>${escapeHtml(_drillTeam)}</b>.<br>
              Check the team name in <code>data/divisions.json</code>.
            </div>
          </div>
        </div>`;
    }
    const { team: t, section } = info;
    const brokers = (t.brokers || []).filter(b => b.name);
    const specs   = (t.specialists || []).filter(s => s.name && !/^Quay 1 Property Specialist/i.test(s.name));
    const contactList = (label, list) => list.length
      ? `<div class="modal-section">
          <div class="modal-section-label">${label}</div>
          <div class="modal-contacts">
            ${list.map(c => `
              <div class="modal-contact">
                <div class="modal-contact-name">${escapeHtml(c.name)}</div>
                <div class="modal-contact-row">
                  ${c.email ? `<a class="dir-link" href="mailto:${escapeHtml(c.email)}">${escapeHtml(c.email)}</a>` : '<span class="muted">no email</span>'}
                </div>
                <div class="modal-contact-row">
                  ${c.phone ? `<a class="dir-link" href="tel:${escapeHtml(c.phone.replace(/\s/g, ''))}">${escapeHtml(c.phone)}</a>` : '<span class="muted">no phone</span>'}
                </div>
              </div>`).join('')}
          </div>
        </div>` : '';

    // Cross-reference with the deals JSON if loaded.
    const dealsRow = (_hubspot && _hubspot.groups)
      ? Object.values(_hubspot.groups).flat().find(r => (r.team || '').toLowerCase().trim() === _drillTeam.toLowerCase().trim())
      : null;
    const dealsSummary = dealsRow ? `
      <div class="modal-section">
        <div class="modal-section-label">HubSpot deals snapshot</div>
        <div class="modal-deals">
          <div><b>${fmt(dealsRow._tot || (dealsRow.total && dealsRow.total.deals) || 0)}</b><span>total</span></div>
          <div><b>${fmt(dealsRow._out || (dealsRow.outdated && dealsRow.outdated.outdated) || 0)}</b><span>outdated</span></div>
          <div><b>${dealsRow.outdated && dealsRow.outdated.pctUpdated != null ? (Number(dealsRow.outdated.pctUpdated) * 100).toFixed(0) + '%' : '-'}</b><span>% updated</span></div>
        </div>
      </div>` : '';

    return `
      <div class="modal-back" data-modal-close></div>
      <div class="modal" role="dialog" aria-label="${escapeHtml(t.name)} details">
        <div class="modal-head">
          <div>
            <h3>${escapeHtml(t.name)}</h3>
            <div class="sub">${escapeHtml(section)}${t.type ? ` · ${escapeHtml(t.type.trim())}` : ''}</div>
          </div>
          <button class="modal-close" data-modal-close aria-label="Close">✕</button>
        </div>
        <div class="modal-body">
          ${t.suburbs ? `
            <div class="modal-section">
              <div class="modal-section-label">Areas covered</div>
              <div class="modal-suburbs">${escapeHtml(t.suburbs)}</div>
            </div>` : ''}
          ${contactList('Brokers', brokers)}
          ${contactList('Property specialists', specs)}
          ${dealsSummary}
          ${(t.hubspot_email || t.hubspot_owner_id) ? `
            <div class="modal-section modal-section--meta">
              <div class="modal-section-label">HubSpot</div>
              <div class="modal-meta-grid">
                ${t.hubspot_email ? `<div><span>Team email</span><a class="dir-link" href="mailto:${escapeHtml(t.hubspot_email)}">${escapeHtml(t.hubspot_email)}</a></div>` : ''}
                ${t.hubspot_owner_id ? `<div><span>Owner ID</span><code>${escapeHtml(t.hubspot_owner_id)}</code></div>` : ''}
                ${t.hubspot_division ? `<div><span>Division</span>${escapeHtml(t.hubspot_division)}</div>` : ''}
              </div>
            </div>` : ''}
        </div>
      </div>`;
  }
  function wireTeamDrillDown() {
    document.querySelectorAll('[data-modal-close]').forEach(el => {
      el.addEventListener('click', closeTeamDrillDown);
    });
    document.addEventListener('keydown', _escClose, { once: true });
  }
  function _escClose(e) {
    if (e.key === 'Escape' && _drillTeam) closeTeamDrillDown();
  }

  function wireHubspot() {
    document.querySelectorAll('#hsGroupSeg button[data-hs-group]').forEach(b => {
      b.addEventListener('click', () => {
        _hubspotGroup = b.dataset.hsGroup;
        render();
      });
    });
    document.querySelectorAll('button[data-hs-filter]').forEach(b => {
      b.addEventListener('click', () => {
        _hubspotFilter = b.dataset.hsFilter;
        render();
      });
    });
    const showEmpty = document.getElementById('hsShowEmpty');
    if (showEmpty) showEmpty.addEventListener('change', (e) => {
      _hubspotShowEmpty = !!e.target.checked;
      render();
    });
    // Clickable team rows → drill-down modal. Use mousedown (not click)
    // so a click that drags off the row doesn't fire, but stop propagation
    // when the user clicks the "↗ open in HubSpot" link in the last col.
    document.querySelectorAll('tr.row-team[data-team-name]').forEach(tr => {
      const open = () => openTeamDrillDown(tr.dataset.teamName);
      tr.addEventListener('click', (ev) => {
        if (ev.target.closest('a, button')) return;
        open();
      });
      tr.addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); open(); }
      });
    });
    document.querySelectorAll('th[data-hs-sort]').forEach(th => {
      th.style.cursor = 'pointer';
      th.addEventListener('click', () => {
        const k = th.dataset.hsSort;
        if (_hubspotSortBy === k) {
          _hubspotSortDir = _hubspotSortDir === 'asc' ? 'desc' : 'asc';
        } else {
          _hubspotSortBy = k;
          // First sort on a stage / pct column = "worst first"
          // (ascending pctUpdated, descending raw counts).
          _hubspotSortDir = (k === 'pctUpdated' || k === 'team') ? 'asc' : 'desc';
        }
        render();
      });
    });
  }

  // ─── Recruitment tab ──────────────────────────────────────────────────
  // Contract request (with provisioning) + Progress report. The contract form
  // generates the MOA, seeds the tracker row, and captures what the hire needs
  // provisioned; the Progress report tracks each candidate from there.
  function renderRecruitment() {
    const seg = (id, label) =>
      `<button class="${_recruitForm === id ? 'active' : ''}" data-rec-form="${id}">${escapeHtml(label)}</button>`;
    const field = (id, label, type, req) =>
      `<label class="rec-field"><span class="rec-label">${escapeHtml(label)}${req ? ' <em>*</em>' : ''}</span>` +
      `<input class="rec-input" id="${id}" name="${id}" type="${type}"${req ? ' required' : ''}></label>`;
    const fileField = (id, label, req) =>
      `<label class="rec-field"><span class="rec-label">${escapeHtml(label)}${req ? ' <em>*</em>' : ''}</span>` +
      `<input class="rec-input rec-file" id="${id}" name="${id}" type="file"${req ? ' required' : ''}></label>`;
    const toggle = (id, label) =>
      `<label class="rec-toggle"><input type="checkbox" id="${id}" name="${id}"><span>${escapeHtml(label)}</span></label>`;
    const submitRow = (txt) =>
      `<div class="rec-actions"><button type="submit" class="rec-submit">${escapeHtml(txt)}</button>` +
      `<span class="rec-note" id="recNote"></span></div>`;
    const selectField = (id, label, optionsHtml, req, hint) =>
      `<label class="rec-field"><span class="rec-label">${escapeHtml(label)}${req ? ' <em>*</em>' : ''}` +
      `${hint ? ` <span class="rec-hint">${escapeHtml(hint)}</span>` : ''}</span>` +
      `<select class="rec-input rec-select" id="${id}" name="${id}"${req ? ' required' : ''}>${optionsHtml}</select></label>`;
    const roField = (id, label) =>
      `<label class="rec-field"><span class="rec-label">${escapeHtml(label)}</span>` +
      `<input class="rec-input" id="${id}" name="${id}" type="text" readonly placeholder="auto-filled from team"></label>`;

    // Broker activities - the 7 definitions from the Broker Agreement template
    // (a "delete inapplicable definition" table; one is kept). `code` is the
    // machine value; `def` is the exact clause text merged into the contract.
    // Residential only for now - commercial is parked (no commercial template yet),
    // so it's kept out of the picker to avoid generating a wrong/blank contract.
    const BROKER_ACTIVITIES = [
      { code: 'sell_res_sb', label: 'Sell · Residential · Broker (SB)', def: 'The selling and/or brokerage of immovable residential property or a broker performing his/her/their functions to such an end; and/or' },
      { code: 'sell_res_jb', label: 'Sell · Residential · Assistant (JB)', def: 'The selling and/or brokerage of immovable residential property or an assistant to a broker performing his/her/their functions to such an end; and/or' },
      { code: 'rent_res_sb', label: 'Rent · Residential · Broker (SB)', def: 'The renting and/or brokerage for rent of immovable residential property or a broker performing his/her/their functions to such an end; and/or' },
      { code: 'rent_res_jb', label: 'Rent · Residential · Assistant (JB)', def: 'The renting and/or brokerage for rent of immovable residential property or an assistant to a broker performing his/her/their functions to such an end; and/or' },
    ];
    const activityOptions = () => BROKER_ACTIVITIES.length
      ? '<option value="">- select activity -</option>' +
        BROKER_ACTIVITIES.map(a => `<option value="${escapeHtml(a.code)}">${escapeHtml(a.label)}</option>`).join('')
      : '<option value="">Options pending…</option>';

    // Team dropdown built from the division directory: grouped by program
    // (section), each option carries its senior broker (first-listed) so the
    // Senior broker field auto-fills on change.
    const teamOptions = () => {
      const secs = (_divisions && _divisions.sections) || [];
      if (!secs.length) return '<option value="">Loading teams…</option>';
      return '<option value="">- select team -</option>' + secs.map(sec => {
        const opts = (sec.teams || []).map(t => {
          const sb = (t.brokers && t.brokers[0]) || {};
          const senior = sb.name || '';
          const seniorEmail = sb.email || '';
          return `<option value="${escapeHtml(t.name)}" data-senior="${escapeHtml(senior)}" data-senior-email="${escapeHtml(seniorEmail)}" data-program="${escapeHtml(sec.name)}">${escapeHtml(t.name)}</option>`;
        }).join('');
        return `<optgroup label="${escapeHtml(sec.name)}">${opts}</optgroup>`;
      }).join('');
    };

    const isBroker = !!(_currentUser && _currentUser.role === 'broker');

    // Requester field. For a broker it is prefilled AND locked (readonly) to
    // their own identity, since a broker can only request contracts as
    // themselves. The backend force-overrides requester_* from the verified
    // JWT, so the lock is honest UX, not the security boundary. For
    // supers/admins it stays an editable field (prefilled in wireRecruitment).
    const requesterField = isBroker
      ? `<label class="rec-field"><span class="rec-label">Your email (CC)</span>` +
          `<input class="rec-input" id="c_requester_email" name="c_requester_email" type="email" readonly` +
          ` value="${escapeHtml((_currentUser && _currentUser.email) || '')}"` +
          ` placeholder="${escapeHtml((_currentUser && _currentUser.name) || 'you')}"></label>`
      : field('c_requester_email', 'Your email (person completing this, CC)', 'email', false);

    // Provisioning toggles - what the new hire needs set up. Captured on the
    // contract request so it flows straight into the tracker (and the Progress
    // report + broker/digest emails) instead of a separate intake step.
    const provisioningSection = `
        <div class="rec-subhead">Provisioning - what do they need?</div>
        <div class="rec-toggles">
          ${PROGRAM_OPTIONS.map(o => toggle('c_prov_' + o.code, o.label)).join('')}
        </div>`;

    const contractForm = `
      <form class="rec-form" id="recFormContract" novalidate>
        <div class="rec-grid">
          ${field('c_fullname', 'Full name', 'text', true)}
          ${field('c_id', 'ID number', 'text', true)}
          ${selectField('c_activity', 'Broker activities', activityOptions(), true, BROKER_ACTIVITIES.length ? '' : 'options pending')}
          ${field('c_start', 'Start date', 'date', true)}
          ${selectField('c_team', 'Team (per program)', teamOptions(), true)}
          ${roField('c_senior', 'Senior broker')}
          ${field('c_commission', 'Commission %', 'number', true)}
          ${field('c_candidate_email', 'Candidate email', 'email', true)}
          ${field('c_senior_email', 'Senior broker email', 'email', true)}
          ${requesterField}
        </div>
        ${provisioningSection}
        ${submitRow('Generate contract')}
      </form>`;

    return `<div class="tab-view">
      <div class="card card-pad">
        <h3 style="margin:0;font-family:var(--serif);font-size:17px;color:var(--ink)">Recruitment</h3>
        <div class="sub" style="margin-top:6px">Broker onboarding - request a contract for a new hire, then track their progress.</div>
        <div class="seg" id="recSeg" style="margin-top:14px">
          ${seg('contract', 'Contract')}${seg('progress', 'Progress report')}
        </div>
      </div>
      <div class="card mt card-pad">
        ${_recruitForm === 'progress' ? renderProgress() : contractForm}
      </div>
    </div>`;
  }

  function wireRecruitment() {
    document.querySelectorAll('#recSeg [data-rec-form]').forEach(b => {
      b.addEventListener('click', () => {
        if (_recruitForm === b.dataset.recForm) return;
        _recruitForm = b.dataset.recForm;
        render();
      });
    });
    // Progress sub-view has its own wiring; the contract/intake wiring below
    // is all id-guarded, so it no-ops when those forms aren't rendered.
    if (_recruitForm === 'progress') { wireProgress(); return; }
    // Team → Senior broker: auto-fill the read-only senior broker from the
    // selected team's option data (first-listed broker for that team).
    const teamSel = document.getElementById('c_team');
    if (teamSel) {
      teamSel.addEventListener('change', () => {
        const opt = teamSel.selectedOptions[0];
        const sr = document.getElementById('c_senior');
        if (sr) sr.value = opt ? (opt.dataset.senior || '') : '';
        // Prefill the senior broker's email from the directory too (the field
        // stays editable, so the user can override if the actual senior isn't
        // the first-listed broker). Removes a manual re-key of a known value.
        const se = document.getElementById('c_senior_email');
        if (se) se.value = opt ? (opt.dataset.seniorEmail || '') : '';
      });
    }
    // Prefill the requester email from the signed-in user. For supers/admins
    // the field stays editable (a PA can swap in the broker's address); for a
    // broker it is rendered readonly and locked to their own identity. Either
    // way the backend derives the authoritative requester from the JWT.
    const reqEmail = document.getElementById('c_requester_email');
    if (reqEmail && !reqEmail.value && _currentUser && _currentUser.email) {
      reqEmail.value = _currentUser.email;
    }
    const form = document.querySelector('.rec-form');
    if (form) {
      form.addEventListener('submit', async (e) => {
        e.preventDefault();
        if (!form.checkValidity()) { form.reportValidity(); return; }
        const note = document.getElementById('recNote');
        if (!RECRUIT_ENDPOINT) {
          if (note) {
            note.textContent = 'Not submitted - backend not connected yet. Nothing was sent.';
            note.className = 'rec-note warn';
          }
          return;
        }
        // Guard against double-submit. Contract generation is not idempotent on
        // the backend (a resubmit re-copies the MOA and re-sends the candidate
        // welcome email), so we block re-entry and disable the button for the
        // whole in-flight window, re-enabling only once the request settles.
        if (form.dataset.submitting === '1') return;
        const submitBtn = form.querySelector('.rec-submit');
        form.dataset.submitting = '1';
        if (submitBtn) submitBtn.disabled = true;
        if (note) { note.textContent = 'Submitting…'; note.className = 'rec-note'; }
        try {
          const fd = {};
          form.querySelectorAll('input, select').forEach(el => {
            if (el.type === 'checkbox') fd[el.id] = el.checked;
            else if (el.type !== 'file') fd[el.id] = el.value;
          });
          const fields = _recruitFields(form.id, fd);
          const files = await _recruitFiles(form);
          // Authenticate with the fresh JWT only. The backend derives the
          // requester from the verified identity (authoritative for brokers,
          // whose requester field is locked) and rejects any unauthenticated
          // request; there is no shared-token fallback.
          const accessToken = await window.AUTH.getAccessToken();
          const res = await fetch(RECRUIT_ENDPOINT, {
            method: 'POST',
            headers: { 'Content-Type': 'text/plain;charset=utf-8' }, // avoids CORS preflight
            body: JSON.stringify({ accessToken, fields, files }),
          });
          const data = await res.json();
          if (data.ok && note) {
            // Brokers must not reach the onboarding Drive folder (it collects the
            // candidate's FICA docs), so only supers/admins get the folder link.
            // The contract PDF the broker just requested is fine to surface.
            const isBrokerUser = !!(_currentUser && _currentUser.role === 'broker');
            const links = [];
            if (!isBrokerUser && data.folderUrl) {
              links.push('<a href="' + data.folderUrl + '" target="_blank" rel="noopener">open folder</a>');
            }
            if (data.pdfUrl) {
              links.push('<a href="' + data.pdfUrl + '" target="_blank" rel="noopener">contract PDF</a>');
            }
            note.innerHTML = 'Done' + (links.length ? ' · ' + links.join(' · ') : '');
            note.className = 'rec-note';
            form.reset();
          } else if (note) {
            note.textContent = 'Error: ' + (data.error || 'unknown'); note.className = 'rec-note warn';
          }
        } catch (err) {
          if (note) { note.textContent = 'Submit failed: ' + err; note.className = 'rec-note warn'; }
        } finally {
          form.dataset.submitting = '';
          if (submitBtn) submitBtn.disabled = false;
        }
      });
    }
  }

  // Map a form's raw field ids to the backend's field names.
  function _recruitFields(formId, fd) {
    // Provisioning toggles ticked on the contract form become the candidate's
    // initial programs, stored on the tracker by the backend (editable later in
    // the Progress report).
    const programs = PROGRAM_OPTIONS
      .filter(o => fd['c_prov_' + o.code])
      .map(o => ({ code: o.code, label: o.label }));
    return {
      full_name: fd.c_fullname, id_number: fd.c_id, activity: fd.c_activity,
      start_date: fd.c_start, team: fd.c_team, senior_broker: fd.c_senior,
      commission: fd.c_commission,
      candidate_email: fd.c_candidate_email, senior_email: fd.c_senior_email,
      // Requester identity scopes "broker sees own candidates" in the
      // progress view. Email comes from the (prefilled, overridable) field;
      // name is taken from the signed-in session.
      requester_name: (_currentUser && _currentUser.name) || '',
      requester_email: fd.c_requester_email,
      programs: programs,
    };
  }
  // Read any file inputs as base64 for the Apps Script to save to Drive.
  async function _recruitFiles(form) {
    const out = [];
    for (const inp of form.querySelectorAll('input[type=file]')) {
      for (const file of (inp.files || [])) {
        out.push({ name: file.name, mimeType: file.type || 'application/octet-stream',
                   dataBase64: await _fileToB64(file) });
      }
    }
    return out;
  }
  function _fileToB64(file) {
    return new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(String(r.result).split(',')[1] || '');
      r.onerror = reject;
      r.readAsDataURL(file);
    });
  }

  // ─── Recruitment → Progress report ────────────────────────────────────
  // Admin-facing candidate tracker. Lists candidates (own for a broker, all
  // for a super/admin) with their onboarding stage, and lets a broker set the
  // programs a new hire needs. Reads / writes via the same Apps Script.
  //
  // SCOPE: loadProgress POSTs the Supabase JWT (kind:'progress', accessToken);
  // the backend verifies it and scopes candidates from that identity. Supers
  // and admins see everyone; a broker sees ONLY candidates they requested
  // (requester_email match; being the team's senior broker does NOT count). We
  // do NOT pass scope/email and NEVER client-side filter. A broker with no real
  // staff.email matches no candidates (the backend's safe default).

  // Master program list, kept client-side so it grows without a backend
  // change. The free-text "Other" row is handled separately (code 'other').
  // Single source of truth for provisioning options, shared by the contract
  // form's "Provisioning" section and the Progress report's per-candidate editor.
  const PROGRAM_OPTIONS = [
    { code: 'cma',      label: 'CMA account' },
    { code: 'dialfire', label: 'Dialfire account' },
    { code: 'whatsapp', label: 'WhatsApp Business' },
    { code: 'training', label: 'Calling training' },
  ];
  // The four onboarding documents surfaced per candidate (backend omits the
  // sensitive bank/tax/ID copies; these are the received-flags it exposes).
  const PROG_DOC_FIELDS = [
    { k: 'bankConf',  label: 'Bank' },
    { k: 'poa',       label: 'POA' },
    { k: 'idRcv',     label: 'ID' },
    { k: 'agreement', label: 'Agreement' },
  ];
  const _MON_SHORT = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  // Format a backend date: "15 Jul" if it's ISO YYYY-MM-DD, else pass through.
  function _fmtProgDate(s) {
    const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(s == null ? '' : s).trim());
    return m ? (Number(m[3]) + ' ' + _MON_SHORT[Number(m[2]) - 1]) : escapeHtml(String(s == null ? '' : s));
  }
  function _candStatus(c) {
    if (!c.allDocsIn)                       return { cls: 'warn', label: 'Awaiting docs' };
    if (!(c.induction && c.induction.wed))  return { cls: 'warn', label: 'Book induction' };
    if (!c.confirmSent)                     return { cls: 'ok',   label: 'Induction set' };
    return { cls: 'ok', label: 'Confirmed' };
  }
  // Normalise a programs list to a comparable string (so "nothing changed"
  // can be detected before POSTing). Only 'other' carries a meaningful note.
  function _programsNorm(list) {
    return (list || [])
      .map(p => (p.code || '') + '|' + (p.code === 'other' ? (p.note || '') : ''))
      .sort().join(',');
  }

  async function loadProgress() {
    if (_progressLoading) return;
    _progressLoading = true;
    _progressError = null;
    try {
      // Reads are authenticated by the Supabase JWT in the POST body (the old
      // GET ?token&scope read has been retired backend-side). The server scopes
      // candidates from the verified identity: supers see all, brokers see only
      // contracts they requested (requester_email match; senior broker does not
      // count). We never pass scope/email and never client-side filter.
      const accessToken = await window.AUTH.getAccessToken();
      const r = await fetch(RECRUIT_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' }, // avoids CORS preflight
        body: JSON.stringify({ kind: 'progress', accessToken }),
      });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      const data = await r.json();
      if (!data || !data.ok) {
        const err = (data && data.error) || 'load failed';
        _progress = null;
        _progressError = (err === 'unauthorized' || err === 'forbidden')
          ? 'Your session could not be verified for recruitment access. Please sign out and back in.'
          : String(err);
        return;
      }
      _progress = data;
    } catch (e) {
      console.warn('[progress] load failed', e);
      _progress = null;
      _progressError = String(e.message || e);
    } finally {
      _progressLoading = false;
      render();
    }
  }

  function renderProgress() {
    if (_progress == null && !_progressLoading && _progressError == null) loadProgress();
    if (_progressLoading || (_progress == null && _progressError == null)) {
      return `<div style="text-align:center;color:var(--muted);padding:44px 20px">Loading candidates…</div>`;
    }
    if (_progressError != null) {
      return `<div style="text-align:center;color:var(--red);padding:32px 20px">
        Couldn't load candidates: ${escapeHtml(_progressError)}.
        <div style="margin-top:12px"><button class="chip" id="progRetry">Try again</button></div>
      </div>`;
    }
    const cands = (_progress && _progress.candidates) || [];
    // Supers and admins see everyone; brokers see only their own. Key the note
    // off that, not isSuper alone, so admins do not read "your candidates".
    const seesAll = !!(_currentUser && (_currentUser.isSuper || _currentUser.isAdmin));
    const scopeNote = seesAll
      ? `Showing all candidates.`
      : `Showing your candidates${_currentUser && _currentUser.name ? ' (' + escapeHtml(_currentUser.name) + ')' : ''}.`;

    if (!cands.length) {
      return `<div style="color:var(--muted);padding:8px 2px 4px">
        <div style="font-size:12.5px;margin-bottom:10px">${scopeNote}</div>
        <div style="text-align:center;padding:40px 20px">No candidates yet. Once a contract is generated it will appear here.</div>
      </div>`;
    }

    const docPill = (ok, label) =>
      `<span class="pill ${ok ? 'ok' : 'bad'}" style="font-size:10.5px;padding:2px 7px" title="${escapeHtml(label)} ${ok ? 'received' : 'outstanding'}">${ok ? '✓' : '✗'} ${escapeHtml(label)}</span>`;
    const docsCell = (docs) => `<div style="display:flex;flex-wrap:wrap;gap:4px">${
      PROG_DOC_FIELDS.map(d => docPill(!!(docs || {})[d.k], d.label)).join('')
    }</div>`;

    const progChip = (p) => {
      const txt = p.code === 'other' ? ('Other: ' + (p.note || '')) : (p.label || p.code || '');
      return `<span class="pill" style="background:var(--sky-tint,#E9F2FB);color:var(--blue-800);font-size:10.5px;padding:2px 8px">${escapeHtml(txt)}</span>`;
    };
    const programsCell = (c) => {
      const list = c.programs || [];
      const chips = list.length
        ? list.map(progChip).join(' ')
        : `<span class="empty" style="color:var(--muted)">none</span>`;
      return `<div style="display:flex;flex-wrap:wrap;gap:4px;align-items:center">${chips}
        <button class="chip" data-prog-edit="${escapeHtml(c.folderId)}" style="font-size:10.5px;padding:3px 9px">${_progressExpanded === c.folderId ? 'Close' : 'Edit'}</button>
      </div>`;
    };

    const inductionCell = (c) => {
      const ind = c.induction || {};
      if (!ind.wed) return `<span class="empty" style="color:var(--muted)">not yet</span>`;
      return `<span style="font-weight:600;color:var(--ink)">Wed ${_fmtProgDate(ind.wed)}<br>Thu ${_fmtProgDate(ind.thu)}</span>`;
    };

    const editorRow = (c) => {
      if (_progressExpanded !== c.folderId) return '';
      const other = (c.programs || []).find(p => p.code === 'other');
      const toggles = PROGRAM_OPTIONS.map(o => {
        const on = (c.programs || []).some(p => p.code === o.code);
        return `<label class="rec-toggle"><input type="checkbox" data-prog-code="${escapeHtml(o.code)}" data-prog-label="${escapeHtml(o.label)}"${on ? ' checked' : ''}><span>${escapeHtml(o.label)}</span></label>`;
      }).join('');
      return `<tr class="prog-panel" data-prog-panel="${escapeHtml(c.folderId)}">
        <td colspan="5" style="background:var(--paper-2);padding:16px 18px">
          <div style="font-family:var(--serif);font-size:12px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--blue-800);margin-bottom:10px">Programs for ${escapeHtml(c.name || c.firstName || 'this candidate')}</div>
          <div class="rec-toggles" style="margin-bottom:12px">${toggles}</div>
          <label class="rec-field" style="margin-bottom:12px">
            <span class="rec-label">Other (free text)</span>
            <input class="rec-input" type="text" data-prog-other placeholder="e.g. Payprop access" value="${escapeHtml(other ? (other.note || '') : '')}">
          </label>
          <div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap">
            <button class="rec-submit" data-prog-save="${escapeHtml(c.folderId)}" style="width:auto">Save programs</button>
            <button class="chip" data-prog-cancel>Cancel</button>
            <span class="prog-save-note" style="font-size:12.5px;font-weight:600;color:var(--muted)"></span>
          </div>
        </td>
      </tr>`;
    };

    const rows = cands.map(c => {
      const st = _candStatus(c);
      const missing = c.allDocsIn ? '' :
        `<div style="font-size:11px;color:var(--muted);margin-top:3px">Missing: ${
          PROG_DOC_FIELDS.filter(d => !(c.docs || {})[d.k]).map(d => escapeHtml(d.label)).join(', ') || 'none'
        }</div>`;
      const desig = [c.team, c.designation].filter(Boolean).map(escapeHtml).join(' · ');
      // The onboarding Drive folder holds the candidate's FICA docs, so it is
      // deliberately NOT surfaced anywhere on this dashboard (for anyone). The
      // backend still omits folderUrl from broker payloads as a second guard.
      return `<tr>
        <td>
          <div class="agent-cell"><div class="agent-name">${escapeHtml(c.name || c.firstName || 'Unnamed')}</div></div>
          ${desig ? `<div style="font-size:11.5px;color:var(--muted);margin-top:2px">${desig}</div>` : ''}
          <div style="margin-top:5px"><span class="pill ${st.cls}">${escapeHtml(st.label)}</span></div>
        </td>
        <td>${escapeHtml(c.requesterName || c.requesterEmail || 'Unknown')}</td>
        <td>${docsCell(c.docs)}${missing}</td>
        <td>${inductionCell(c)}</td>
        <td>${programsCell(c)}</td>
      </tr>${editorRow(c)}`;
    }).join('');

    return `<div>
      <div style="display:flex;flex-wrap:wrap;gap:8px;align-items:baseline;justify-content:space-between;margin-bottom:12px">
        <div class="sub">${scopeNote} ${cands.length} candidate${cands.length === 1 ? '' : 's'}.</div>
        <button class="chip" id="progRefresh">Refresh</button>
      </div>
      <div class="tbl-wrap"><table class="tbl">
        <thead><tr>
          <th style="text-align:left">Candidate</th>
          <th style="text-align:left">Requester</th>
          <th style="text-align:left">Documents</th>
          <th style="text-align:left">Induction</th>
          <th style="text-align:left">Programs</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table></div>
    </div>`;
  }

  function wireProgress() {
    const retry = document.getElementById('progRetry');
    if (retry) retry.addEventListener('click', () => { _progressError = null; _progress = null; loadProgress(); });
    const refresh = document.getElementById('progRefresh');
    if (refresh) refresh.addEventListener('click', () => { _progress = null; _progressExpanded = null; loadProgress(); });

    document.querySelectorAll('[data-prog-edit]').forEach(b => {
      b.addEventListener('click', () => {
        const fid = b.dataset.progEdit;
        _progressExpanded = (_progressExpanded === fid) ? null : fid;
        render();
      });
    });
    document.querySelectorAll('[data-prog-cancel]').forEach(b => {
      b.addEventListener('click', () => { _progressExpanded = null; render(); });
    });
    document.querySelectorAll('[data-prog-save]').forEach(b => {
      b.addEventListener('click', () => _savePrograms(b.dataset.progSave));
    });
  }

  async function _savePrograms(folderId) {
    const panel = document.querySelector('.prog-panel[data-prog-panel]');
    if (!panel) return;
    const note = panel.querySelector('.prog-save-note');
    const setNote = (msg, colour) => { if (note) { note.textContent = msg; note.style.color = colour || 'var(--muted)'; } };

    const programs = [];
    panel.querySelectorAll('input[type=checkbox][data-prog-code]').forEach(cb => {
      if (cb.checked) programs.push({ code: cb.dataset.progCode, label: cb.dataset.progLabel });
    });
    const otherInput = panel.querySelector('input[data-prog-other]');
    const otherNote = otherInput ? otherInput.value.trim() : '';
    if (otherNote) programs.push({ code: 'other', label: 'Other', note: otherNote });

    const cand = ((_progress && _progress.candidates) || []).find(c => c.folderId === folderId);
    if (cand && _programsNorm(cand.programs || []) === _programsNorm(programs)) {
      setNote('No changes to save.');
      return;
    }
    const btn = panel.querySelector('[data-prog-save]');
    if (btn) btn.disabled = true;
    setNote('Saving…');
    try {
      // Authenticate with the fresh JWT only so the backend can enforce
      // ownership (a broker may only edit their own candidate). No shared token.
      const accessToken = await window.AUTH.getAccessToken();
      const res = await fetch(RECRUIT_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' }, // avoids CORS preflight
        body: JSON.stringify({ kind: 'set_programs', folderId, programs, accessToken }),
      });
      const data = await res.json();
      if (data && data.ok) {
        if (cand) cand.programs = data.programs || programs;
        _progressExpanded = null;
        render();
      } else {
        setNote('Error: ' + ((data && data.error) || 'unknown'), 'var(--red)');
        if (btn) btn.disabled = false;
      }
    } catch (err) {
      setNote('Save failed: ' + err, 'var(--red)');
      if (btn) btn.disabled = false;
    }
  }

  // ─── Boot + auth gate ─────────────────────────────────────────────────
  // Team Insights is admin-only. app.js never loads data or renders a tab
  // until auth.js confirms a super/admin Supabase session; it fails closed
  // (shows the login gate) if the auth layer or session can't be verified.
  function _wireTabsOnce() {
    // Tab nav lives in index.html - wire it once after sign-in.
    document.querySelectorAll('#tabNav .tab-btn').forEach(b => {
      b.addEventListener('click', () => {
        if (_tab === b.dataset.tab) return;
        _tab = b.dataset.tab;
        _drillTeam = null;   // close any open modal when switching tabs
        render();
      });
    });
  }

  function enterApp(user) {
    _currentUser = user || null;   // { username, name, email, isSuper, isAdmin, isBroker, role }
    document.body.classList.remove('pre-auth');
    const gate = document.getElementById('loginGate');
    if (gate) gate.remove();
    const so = document.getElementById('signOutBtn');
    if (so) {
      so.hidden = false;
      const who = document.getElementById('signOutWho');
      if (who && user && user.name) who.textContent = user.name.split(' ')[0] + ' · ';
      so.addEventListener('click', async () => {
        so.disabled = true;
        await window.AUTH.signOut();
        location.reload();
      });
    }
    // Broker AND payroll logins are gated to the Recruitment area only: hide the
    // whole tab nav and pin the active view to Recruitment. Supers/admins keep
    // the full nav. The real boundary is server-side (Supabase JWT checked by
    // the Apps Script); this UI lock is just honest UX. Creating these accounts
    // is the user's job, done per account.
    if (_currentUser && (_currentUser.role === 'broker' || _currentUser.role === 'payroll')) {
      _tab = 'recruitment';
      const nav = document.getElementById('tabNav');
      if (nav) nav.style.display = 'none';
    }
    _wireTabsOnce();
    render();
  }

  // PIN-pad sign-in, matched to the Performance Dashboard. Staff PINs are
  // always 6 digits (admin-set-pin refuses anything else), so we auto-submit
  // once six are entered.
  function showLoginGate(prefillError) {
    const gate  = document.getElementById('loginGate');
    const errEl = document.getElementById('loginError');
    const dots  = document.getElementById('pinDots');
    const keypad = document.getElementById('loginKeypad');
    const userIn = document.getElementById('loginUser');
    if (prefillError && errEl) { errEl.textContent = prefillError; errEl.hidden = false; }
    if (!gate || !keypad) return;

    let pin = '';
    let busy = false;
    const paintDots = () => {
      if (!dots) return;
      Array.from(dots.children).forEach((d, i) =>
        d.classList.toggle('filled', i < pin.length));
    };
    const setError = (msg) => {
      if (!errEl) return;
      errEl.textContent = msg || '';
      errEl.hidden = !msg;
    };

    async function submit() {
      if (busy) return;
      const u = (userIn && userIn.value || '').trim();
      if (!u) { setError('Enter your username first.'); flash(); pin = ''; paintDots(); return; }
      if (pin.length !== 6) return;
      busy = true; setError('');
      let r;
      try { r = await window.AUTH.signIn(u, pin); }
      catch (_) { r = { ok: false, error: 'Sign-in service unavailable — try again.' }; }
      if (r && r.ok) { enterApp(r.user); return; }
      busy = false;
      setError((r && r.error) || 'Sign-in failed.');
      flash(); pin = ''; paintDots();
    }
    function flash() {
      gate.classList.add('pin-error');
      setTimeout(() => gate.classList.remove('pin-error'), 500);
    }
    function press(d) {
      if (busy || pin.length >= 6) return;
      pin += d; paintDots();
      if (pin.length === 6) submit();
    }

    keypad.querySelectorAll('.key[data-d]').forEach(b =>
      b.addEventListener('click', () => { setError(''); press(b.dataset.d); }));
    const back = keypad.querySelector('.key[data-back]');
    if (back) back.addEventListener('click', () => { pin = pin.slice(0, -1); paintDots(); });
    const clr = keypad.querySelector('.key[data-clear]');
    if (clr) clr.addEventListener('click', () => { pin = ''; setError(''); paintDots(); });

    // Physical keyboard support (desktop).
    document.addEventListener('keydown', (e) => {
      if (!document.getElementById('loginGate')) return; // app already entered
      if (e.key >= '0' && e.key <= '9') { setError(''); press(e.key); }
      else if (e.key === 'Backspace' && document.activeElement !== userIn) {
        pin = pin.slice(0, -1); paintDots();
      } else if (e.key === 'Enter') { submit(); }
    });

    if (userIn) userIn.focus();
  }

  document.addEventListener('DOMContentLoaded', async () => {
    // Fail closed: if the auth layer didn't load, never reveal the app.
    if (!window.AUTH || !window.supabase) {
      showLoginGate('Could not reach the sign-in service. Refresh to try again.');
      return;
    }
    let user = null;
    try { user = await window.AUTH.getSession(); } catch (_) { user = null; }
    if (user) enterApp(user);
    else showLoginGate();
  });
})();
